apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
    tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80