apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data: 
  DB_HOST: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:         #these are replicaset service labels
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:       #these are used to select the pod to create replicas
    matchLabels:  #matchlabels should match with pod level labels 
      app: backend
      tier: api
      project: expense
  template:       #this is the pod definition
    metadata:
      labels:     #these labels are belongs to pod
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: ramanji4/backend:{{ .Values.deployment.imageVersion }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:      #limits should be greater than or equal to requests
            cpu: 100m
            memory: 128Mi
        envFrom:
          configMapRef:
            name: backend

---

apiVersion: v1
apiVersion: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpuUtilization }}